import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Mock Interview",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
    <html lang="en">
      <body 
        className={`${inter.className} bg-gradient-to-b from-gray-900 to-black`}
      >
          <ClerkProvider>
        <Header />
        <main className="">{children}</main>
        <Toaster />
        </ClerkProvider>
      </body>
      
    </html>
  
  );
}
